
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  labels:
    gitops.ownedBy: openshift-gitops
    category: apps
    projectId: ${{values.componentId}}
    rht-gitops.com/openshift-gitops: ${{values.componentId}}
  name: ${{values.componentId}}-prod
spec:
  destination:
    namespace: ${{values.componentId}}-prod
    server: https://kubernetes.default.svc
  project: ${{values.componentId}}
  source:
    path: overlays/prod
    repoURL: https://github.com/pittar-rhdh/${{values.repo}}-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
