apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: quay-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          tekton.dev/docker-0: https://quay.io
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: QUAYIO_DOCKERCFG
