apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: github-software-template-collection
  description: A collection of Backstage Golden Path Templates for Github
spec:
  type: url
  targets:
    - https://github.com/pittar-rhdh/software-templates/blob/main/gpts/github/python/basic/template.yaml
