site_name: ${{ values.componentId }}
site_description: ${{ values.description }}
repo_url: https://github.com/pittar-rhdh/${{values.repo}}

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - ${{ values.componentId }} Documentation: index.md