namespace: ${{values.name}}-cicd

resources:
  - githubsecret.yaml
  - triggerbinding.yaml
  - pr-triggertemplate.yaml
  - pr-trigger.yaml
  - build-triggertemplate.yaml
  - build-trigger.yaml
  - eventlistener.yaml
  - eventlistenerroute.yaml