namespace: ${{values.componentId}}-cicd

resources:
  - githubsecret.yaml
  - build-triggerbinding.yaml
  - pr-triggerbinding.yaml
  - pr-triggertemplate.yaml
  - pr-trigger.yaml
  - build-triggertemplate.yaml
  - build-trigger.yaml
  - eventlistener.yaml
  - eventlistenerroute.yaml