apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: basic-markdown
  title: "Basic Markdown Repository"
  description: Template to create a basic Markdown repository.
  tags:
    - markdown
    - ai
spec:
  owner: default/teamlead
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
      properties:
        repoName:
          type: string
          title: Repository Name
    - title: Component Information
      required:
        - owner
        - description
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        description:
          title: Description
          type: string
          description: Project description. Used in documentation.
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          componentId: ${{ parameters.repoName }}
          name: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          repo: ${{ parameters.repoName }}
    - id: publish-repository
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: 'github.com?repo=${{ parameters.repoName }}&owner=pittar-rhdh'
        repoVisibility: public
        description: Repository created by Backstage template
        topics: ['backstage', 'template', 'markdown']
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-repository'].output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps['publish-repository'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}