apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: basic-quarkus
  title: "Basic Quarkus Application"
  description: Template to create a basic Quarkus application under pittar-rhdh.
  tags:
    - quarkus
    - starter
    - java21
spec:
  owner: default/teamlead
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
      properties:
        repoName:
          type: string
          title: Repository Name
          description: Name of the GitHub repository
          # Added a pattern to ensure valid GitHub repo names
          pattern: '^[a-zA-Z0-9_\-\.]+$'
    - title: Component Information
      required:
        - componentId
        - name
        - owner
        - groupId
        - description
      properties:
        componentId:
          title: Component ID
          type: string
          description: Unique name of the Project. Lower case with no special characters.
          default: myquarkusapp
          pattern: '^[a-z0-9\-]+$'
          ui:help: Used as the component ID and Maven artifact ID.
        name:
          title: Name
          type: string
          description: Human readable name of the component.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        groupId:
          title: Group ID
          type: string
          default: ca.pitt.demo.idp
          description: Maven Group ID.
        description:
          title: Description
          type: string
          description: Project description.
        webhookSecret:
          title: Webhook Secret
          type: string
          default: a6j2h82j
          description: Secret value to authenticate the web hook.

  steps:
    - id: fetch
      name: Fetch Code Template
      action: fetch:template
      input:
        url: ./skeleton/source
        targetPath: ./source
        values:
          componentId: ${{ parameters.componentId }}
          name: ${{ parameters.name }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.componentId }}
          javaPackageName: '${{ parameters.groupId | replace(".", "/") }}/${{ parameters.componentId }}'
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          repo: ${{ parameters.repoName }}

    - id: publish-repository
      name: Publish Repository
      action: publish:github
      input:
        # Enforcing the pittar-rhdh organization here
        repoUrl: 'github.com?repo=${{ parameters.repoName }}&owner=pittar-rhdh'
        repoVisibility: public
        description: Repository created by Backstage template
        topics: ['backstage', 'template', 'quarkus']
        sourcePath: ./source

    - id: fetch-gitops
      name: Fetch GitOps Template
      action: fetch:template
      input:
        url: ./skeleton/gitops
        targetPath: ./gitops
        values:
          componentId: ${{ parameters.componentId }}
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          repo: ${{ parameters.repoName }}

    - id: publish-gitops-repository
      name: Publish GitOps Repository
      action: publish:github
      input:
        # Enforcing the pittar-rhdh organization here
        repoUrl: 'github.com?repo=${{ parameters.repoName }}-gitops&owner=pittar-rhdh'
        repoVisibility: public
        description: Repository created by Backstage template
        topics: ['backstage', 'template', 'quarkus']
        sourcePath: ./gitops

    - id: create-webhook
      name: Create GitHub Webhook
      action: github:webhook
      input:
        # FIX: We use the EXACT same string format as the publish step
        repoUrl: 'github.com?repo=${{ parameters.repoName }}&owner=pittar-rhdh'
        # FIX: Added https:// prefix
        webhookUrl: 'https://el-github-pr-listener-${{ parameters.componentId }}-cicd.apps.prime.pitt.ca'
        webhookSecret: ${{ parameters.webhookSecret }}
        contentType: json
        insecureSsl: false
        events: 
          - push
          - pull_request

    - id: createArgocdResourcesCICD
      name: Create the ArgoCD Resources for CICD
      action: argocd:create-resources
      input:
        appName: ${{ parameters.componentId }}-cicd
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: openshift-gitops
        namespace: '*'
        repoUrl: ${{ steps.publishGitOps.output.remoteUrl }}
        labelValue: ${{ parameters.componentId }}
        path: 'argocd/cicd'

    - id: createArgocdResourcesDev
      name: Create the ArgoCD Resources in DEV
      action: argocd:create-resources
      input:
        appName: ${{ parameters.componentId }}-dev
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: openshift-gitops
        namespace: '*'
        repoUrl: ${{ steps.publishGitOps.output.remoteUrl }}
        labelValue: ${{ parameters.componentId }}
        path: 'argocd/dev'

    - id: createArgocdResourcesTest
      name: Create the ArgoCD Resources in TEST
      action: argocd:create-resources
      input:
        appName: ${{ parameters.componentId }}
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: openshift-gitops
        namespace: '*'
        repoUrl: ${{ steps.publishGitOps.output.remoteUrl }}
        labelValue: ${{ parameters.componentId }}
        path: 'argocd/test'


    - id: createArgocdResourcesProd
      name: Create the ArgoCD Resources in PROD
      action: argocd:create-resources
      input:
        appName: ${{ parameters.componentId }}-prod
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: openshift-gitops
        namespace: '*'
        repoUrl: ${{ steps.publishGitOps.output.remoteUrl }}
        labelValue: ${{ parameters.componentId }}
        path: 'argocd/prod'

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        catalogInfoUrl: 'https://github.com/pittar-rhdh/${{ parameters.repoName }}/blob/main/catalog-info.yaml'

  output:
    links:
      - title: Open in Dev Spaces
        url: https://devspaces.apps.prime.pitt.ca/#${{ steps['publish-repository'].output.remoteUrl }}
      - title: Source Repository
        url: ${{ steps['publish-repository'].output.remoteUrl }}
      - title: GitOps Repository
        url: ${{ steps['publish-gitops-repository'].output.remoteUrl }}
      - title: Open Component in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
