apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "0"
  name: ${{values.componentId}}
imagePullSecrets:
  - name: quay-creds
