apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ai-pr-review
spec:
  params:
    - default: pittar-sandbox/image-inspector
      name: GIT_REPO
      type: string
    - name: PR_NUMBER
      type: string
  tasks:
    - name: pr-review
      params:
        - name: repo
          value: $(params.GIT_REPO)
        - name: pullRequestNumber
          value: $(params.PR_NUMBER)
        - name: githubHost
          value: 'https://api.github.com'
        - name: apiBaseUrl
          value: 'https://rhaiis-inference-demo.apps.prime.pitt.ca/v1'
        - name: apiModel
          value: gemma-4-e2b-it
        - name: excludePatterns
          value: '*.txt,package-lock.json,yarn.lock,*.png,*.jpg'
        - name: dryRun
          value: 'false'
        - name: debug
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: ai-code-review
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: shared-workspace
          workspace: workspace
  workspaces:
    - name: workspace
