namespace: ${{values.componentId}}-dev

resources:
  - namespace.yaml
  - ../../base/database
  - ../../base/app

images:
  - name: ${{values.componentId}}
    newName: quay.io/pittar-rhdh/${{values.componentId}}
    newTag: latest
